name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Install deps
      run: yarn install --ignore-engines
    - name: Move to Android folder
      run: ls -lra
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
    - name: Build with Gradle
      run: cd android && ./gradlew assembleRelease
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: my-app
        path: android/app/build/outputs/apk/release/app-dev-release.apk     
